### ISSUE TITLE
Address security alerts

### ISSUE THREAD

**Issue by dmalan** [cs50/publish50-electron#64]
E.g., https://github.com/cs50/publish50-electron/network/alert/yarn.lock/http-proxy/open.

**Comment by rongxin-liu** [comment]
[https://github.com/cs50/publish50-electron/commit/d2b5e3621725e2b984dd57e90cf5ccad38ade3b2](https://github.com/cs50/publish50-electron/commit/d2b5e3621725e2b984dd57e90cf5ccad38ade3b2)
